baseURL: https://mywebsiteportio.netlify.app/
languageCode: en-us
paginate: 6
theme: portio-hugo
title: Portio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: All Projects
      url: 'blog'
      weight: 2
  sitemap:
    - name: Home
      url: '#home'
      weight: 1
    - name: All Projects
      url: 'blog'
      weight: 2
params:
  address:
    address: Regent's Park, London, UK
    email: fmizrahi.mam2022@london.edu
    phone: +33 6 98 73 40 39
  blogPageURL: blog
  contactLink: contact
  footerLogo: images/contact/lbs_logo_05x05.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/contact/lbs_logo_025x025.png
  map:
    APIkey: YOUR GOOGLE MAP API
    latitude: '23.7783741'
    longitude: '90.3746808'
    pinImage: images/pin.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/francois-mizrahi/
      weight: 1
