baseURL: https://www.francoismizrahi.com/
languageCode: en-us
paginate: 6
theme: portio-hugo
title: Portio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: All Projects
      url: 'blog'
      weight: 2
    - name: Contact
      url: 'contact'
      weight: 3
  sitemap:
    - name: Home
      url: '#home'
      weight: 1
    - name: All Projects
      url: 'blog'
      weight: 2
    - name: Contact
      url: 'contact'
      weight: 3
params:
  address:
    address: Regent's Park, London, UK
    email: francois.mizrahi@gmail.com
    phone: +33 6 98 73 40 39
  blogPageURL: blog
  contactLink: contact
  footerLogo: images/contact/lbs_logo_05x05.png
  formspreeURL: https://formspree.io/f/mnqlwbae
  logo: images/contact/lbs_logo_025x025.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/francois-mizrahi/
      weight: 1
